name: flow1
on: 
  schedule:
    - cron: "10 0 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node index.js