name: knowCar
on: 
  workflow_dispatch:
    #branches:
    #  - main
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
  schedule:
    - cron: "18 1,8 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    env:
      EMAIL_NAME: ${{ secrets.EMAIL_NAME }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node knowCar.js
        # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update resource json"
          git push