name: nba2
on: 
  workflow_dispatch:
    #branches:
    #  - main
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
  schedule:
    - cron: "05 7 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node nba.js
                    # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update nbaRes.js"
          git push