name: Update README

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'description'
        required: false 
        type: boolean 
  schedule:
    - cron: '30 1 */9 * *'
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      EMAIL_NAME: ${{ secrets.EMAIL_NAME }}

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node updateReadme.js
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update READMME"
          git push