name: updateCountDay
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
  schedule:
    - cron: "55 23 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  

      - name: Setup Node.js
        uses: actions/setup-node@v2  
        with:
          node-version: '14'

      - name: npm install
        run: npm install
      
      - name: Start task
        run: node updateCountDay.js
      # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update dayRes.js"
          git push